[package]
name = "troxel"
version = "0.1.0"
authors = ["Sebastian Strobl <Sebastian@Strobl.net>"]
edition = "2018"
# [features]
# default = ["vulkan"]
# metal = ["gfx-backend-metal"]
# dx12 = ["gfx-backend-dx12"]
# vulkan = ["gfx-backend-vulkan"]

[dependencies]
bincode = "1.2.1"
winit = "0.22.1"
gfx-hal = "0.5.0"
glsl-to-spirv = "0.1.7"
image = "0.23.4"
serde = { version = "1.0.110", features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies.backend]
package = "gfx-backend-metal"
version = "=0.5.1"

[target.'cfg(windows)'.dependencies.backend]
package = "gfx-backend-dx12"
version = "=0.5.0"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.backend]
package = "gfx-backend-vulkan"
version = "=0.5.1"