[package]
name = "acute"
version = "0.0.1"
authors = ["Sebastian Strobl <Sebastian@Strobl.net>"]
edition = "2018"
description = "Modular Data Driven Physics and Render Engine for the rust programming language."
license = "Apache-2.0"
repository = "https://github.com/tryworks/acute"
keywords = ["acute"]
categories = ["game-engines", "graphics", "gui", "rendering", "science"]
exclude = ["old/"]

# this is not a real "bin" it's just for testing purposes!
[[example]]
name = "testing_example"
path = "examples/basic.rs"

[[bin]]
name = "testing"
path = "src/testing.rs"

[lib]
name = "acute"
path = "src/lib.rs"

[dependencies]
acute_core = { version = "0.1.0", path = "crates/acute_core" }
acute_app = { version = "0.1.1", path = "crates/acute_app" }
acute_ecs = { version = "0.1.0", path = "crates/acute_ecs" }
acute_render = { version = "0.1.0", path = "crates/acute_render" }
acute_render_backend = { version = "0.1.0", path = "crates/acute_render_backend" }
acute_input = { version = "0.1.0", path = "crates/acute_input" }
acute_scenes = { version = "0.1.0", path = "crates/acute_scenes" }
acute_window = { version = "0.1.0", path = "crates/acute_window" }
acute_assets = { version = "0.1.0", path = "crates/acute_assets" }