[package]
name = "acute_app"
version = "0.1.0"
authors = ["Sebatsian Strobl <Sebastian@Strobl.net>"]
edition = "2018"
license = "Apache 2.0"
repository = "https://github.com/tryworks/acute"
keywords = ["acute"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acute_core = { version = "0.1.0", path = "../acute_core" }
acute_ecs = { version = "0.1.0", path = "../acute_ecs" }
acute_scenes = { version = "0.1.0", path = "../acute_scenes" }
acute_window = { version = "0.1.0", path = "../acute_window" }
futures = "0.3.5"