[package]
name = "acute_app"
version = "0.1.2"
authors = ["Sebatsian Strobl <Sebastian@Strobl.net>"]
edition = "2018"
description = "app sub-crate of acute"
license = "Apache-2.0"
repository = "https://github.com/tryworks/acute"
keywords = ["acute"]

[dependencies]
acute_core = { version = "*", path = "../acute_core" }
acute_ecs = { version = "*", path = "../acute_ecs" }
acute_scenes = { version = "*", path = "../acute_scenes" }
acute_window = { version = "*", path = "../acute_window" }
acute_render_backend = { version = "*", path = "../acute_render_backend" }

futures = "0.3.5"