[package]
name = "acute_ecs"
version = "0.1.0"
authors = ["Sebatsian Strobl <Sebastian@Strobl.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.2.4"