[package]
name = "acute_window"
version = "0.1.0"
authors = ["Sebatsian Strobl <Sebastian@Strobl.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22.2"
acute_ecs = { version = "0.1.0", path = "../acute_ecs" }