[package]
name = "acute_vulkan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acute_ecs = { version = "0.1", path = "../acute_ecs" }
acute_app = { version = "0.1", path = "../acute_app" }